version: '3.8' # Рекомендуется использовать версию 3.x

services:

      
  jmeter:
    # Используем собственный образ, созданный из Dockerfile ***
    build: . # Указывает Docker Compose, что нужно собрать образ из текущей директории
    image: my-jmeter-runner:latest # Имя вашего нового образа (выберите любое, но запомните его)
    container_name: jmeter
    #Volumes for tests and reports
    volumes:
      - ./jmeter_tests:/jmeter_tests # Тестовые планы и отчеты будут здесь
      # Нет необходимости монтировать jmeter_plugins отдельно, так как они уже скопированы в образ
    working_dir: /jmeter_tests # Рабочая директория внутри контейнера


    #command: [] # Если вы хотите, чтобы JMeterRunner сам запускался, оставьте пустым
    # Если вы хотите передать какие-то аргументы в main метод JMeterRunner:
    # command: ["--threads", "10", "--duration", "60"] # Пример

    #entrypoint: /bin/sh
    #command: -c "sleep 365d"

    entrypoint: ["java"]
    command: ["-cp", "/opt/apache-jmeter-5.6.3/lib/*:/opt/apache-jmeter-5.6.3/lib/ext/*:/opt/apache-jmeter-5.6.3/lib/ext/kafka_samplers.jar", "org.solutions.jmeter_solution3.sender.JMeterRunner"]
    depends_on:
      - kafka
